version: '3'

services:

 python:
  build:
   context: . # build the image for the web service from the dockerfile 
   dockerfile: Dockerfile
  env_file:
    - .env
  ports: #external:container
    - 80:80
  restart: "on-failure"
